name: calorie_counter
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.1.2
  flutter_speed_dial: ^7.0.0
  cupertino_icons: ^1.0.8
  easy_date_timeline: ^1.1.3
  fl_chart: ^0.69.0
  intl: ^0.19.0
  sqflite: ^2.3.3+2
  path: ^1.8.0
  flutter_material_color_picker: ^1.2.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
